---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: k8s-simple-sample
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/mombe090/k8s-simple-sample

